import type { Coin } from "./model";

export const popularCoins: Coin[] = [
  { name: "Bitcoin", symbol: "BTC", tradingViewSymbol: "BINANCE:BTCUSDT" },
  { name: "Ethereum", symbol: "ETH", tradingViewSymbol: "BINANCE:ETHUSDT" },
  { name: "BNB", symbol: "BNB", tradingViewSymbol: "BINANCE:BNBUSDT" },
  { name: "Solana", symbol: "SOL", tradingViewSymbol: "BINANCE:SOLUSDT" },
  { name: "XRP", symbol: "XRP", tradingViewSymbol: "BINANCE:XRPUSDT" },
  { name: "Dogecoin", symbol: "DOGE", tradingViewSymbol: "BINANCE:DOGEUSDT" },
  { name: "Cardano", symbol: "ADA", tradingViewSymbol: "BINANCE:ADAUSDT" },
  { name: "TRON", symbol: "TRX", tradingViewSymbol: "BINANCE:TRXUSDT" },
  { name: "Avalanche", symbol: "AVAX", tradingViewSymbol: "BINANCE:AVAXUSDT" },
  { name: "Shiba Inu", symbol: "SHIB", tradingViewSymbol: "BINANCE:SHIBUSDT" },
  { name: "Polkadot", symbol: "DOT", tradingViewSymbol: "BINANCE:DOTUSDT" },
  { name: "Chainlink", symbol: "LINK", tradingViewSymbol: "BINANCE:LINKUSDT" },
  { name: "Polygon Ecosystem Token", symbol: "POL", tradingViewSymbol: "BINANCE:POLUSDT" },
  { name: "Litecoin", symbol: "LTC", tradingViewSymbol: "BINANCE:LTCUSDT" },
  { name: "Bitcoin Cash", symbol: "BCH", tradingViewSymbol: "BINANCE:BCHUSDT" },
  { name: "Uniswap", symbol: "UNI", tradingViewSymbol: "BINANCE:UNIUSDT" },
  { name: "Cosmos", symbol: "ATOM", tradingViewSymbol: "BINANCE:ATOMUSDT" },
  { name: "Ethereum Classic", symbol: "ETC", tradingViewSymbol: "BINANCE:ETCUSDT" },
  { name: "Stellar", symbol: "XLM", tradingViewSymbol: "BINANCE:XLMUSDT" },
  { name: "NEAR Protocol", symbol: "NEAR", tradingViewSymbol: "BINANCE:NEARUSDT" },
  { name: "Aptos", symbol: "APT", tradingViewSymbol: "BINANCE:APTUSDT" },
  { name: "Arbitrum", symbol: "ARB", tradingViewSymbol: "BINANCE:ARBUSDT" },
  { name: "Optimism", symbol: "OP", tradingViewSymbol: "BINANCE:OPUSDT" },
  { name: "Filecoin", symbol: "FIL", tradingViewSymbol: "BINANCE:FILUSDT" },
  { name: "Internet Computer", symbol: "ICP", tradingViewSymbol: "BINANCE:ICPUSDT" },
  { name: "Injective", symbol: "INJ", tradingViewSymbol: "BINANCE:INJUSDT" },
  { name: "Sui", symbol: "SUI", tradingViewSymbol: "BINANCE:SUIUSDT" },
  { name: "Sei", symbol: "SEI", tradingViewSymbol: "BINANCE:SEIUSDT" },
  { name: "Render", symbol: "RENDER", tradingViewSymbol: "BINANCE:RENDERUSDT" },
  { name: "dogwifhat", symbol: "WIF", tradingViewSymbol: "BINANCE:WIFUSDT" },
  { name: "Pepe", symbol: "PEPE", tradingViewSymbol: "BINANCE:PEPEUSDT" },
  { name: "Artificial Superintelligence Alliance", symbol: "FET", tradingViewSymbol: "BINANCE:FETUSDT" },
  { name: "Immutable", symbol: "IMX", tradingViewSymbol: "BINANCE:IMXUSDT" },
  { name: "Aave", symbol: "AAVE", tradingViewSymbol: "BINANCE:AAVEUSDT" },
  { name: "The Graph", symbol: "GRT", tradingViewSymbol: "BINANCE:GRTUSDT" },
  { name: "THORChain", symbol: "RUNE", tradingViewSymbol: "BINANCE:RUNEUSDT" },
  { name: "Lido DAO", symbol: "LDO", tradingViewSymbol: "BINANCE:LDOUSDT" },
  { name: "Algorand", symbol: "ALGO", tradingViewSymbol: "BINANCE:ALGOUSDT" },
  { name: "VeChain", symbol: "VET", tradingViewSymbol: "BINANCE:VETUSDT" },
  { name: "Flow", symbol: "FLOW", tradingViewSymbol: "BINANCE:FLOWUSDT" },
  { name: "Decentraland", symbol: "MANA", tradingViewSymbol: "BINANCE:MANAUSDT" },
  { name: "The Sandbox", symbol: "SAND", tradingViewSymbol: "BINANCE:SANDUSDT" },
  { name: "Theta Network", symbol: "THETA", tradingViewSymbol: "BINANCE:THETAUSDT" },
  { name: "EOS", symbol: "EOS", tradingViewSymbol: "BINANCE:EOSUSDT" },
  { name: "Kaspa", symbol: "KAS", tradingViewSymbol: "MEXC:KASUSDT" },
  { name: "Hedera", symbol: "HBAR", tradingViewSymbol: "BINANCE:HBARUSDT" },
  { name: "Quant", symbol: "QNT", tradingViewSymbol: "BINANCE:QNTUSDT" },
  { name: "Jupiter", symbol: "JUP", tradingViewSymbol: "BINANCE:JUPUSDT" },
  { name: "Celestia", symbol: "TIA", tradingViewSymbol: "BINANCE:TIAUSDT" },
  { name: "Stacks", symbol: "STX", tradingViewSymbol: "BINANCE:STXUSDT" },
  { name: "Maker", symbol: "MKR", tradingViewSymbol: "BINANCE:MKRUSDT" },
  { name: "Ethereum Name Service", symbol: "ENS", tradingViewSymbol: "BINANCE:ENSUSDT" },
  { name: "Pendle", symbol: "PENDLE", tradingViewSymbol: "BINANCE:PENDLEUSDT" },
  { name: "Ondo", symbol: "ONDO", tradingViewSymbol: "BINANCE:ONDOUSDT" },
  { name: "Gala", symbol: "GALA", tradingViewSymbol: "BINANCE:GALAUSDT" },
  { name: "Pyth Network", symbol: "PYTH", tradingViewSymbol: "BINANCE:PYTHUSDT" },
  { name: "Starknet", symbol: "STRK", tradingViewSymbol: "BINANCE:STRKUSDT" },
  { name: "Aevo", symbol: "AEVO", tradingViewSymbol: "BINANCE:AEVOUSDT" },
  { name: "Worldcoin", symbol: "WLD", tradingViewSymbol: "BINANCE:WLDUSDT" },
  { name: "JasmyCoin", symbol: "JASMY", tradingViewSymbol: "BINANCE:JASMYUSDT" },
  { name: "BOOK OF MEME", symbol: "BOME", tradingViewSymbol: "BINANCE:BOMEUSDT" },
  { name: "Bonk", symbol: "BONK", tradingViewSymbol: "BINANCE:BONKUSDT" },
  { name: "FLOKI", symbol: "FLOKI", tradingViewSymbol: "BINANCE:FLOKIUSDT" },
  { name: "Curve DAO", symbol: "CRV", tradingViewSymbol: "BINANCE:CRVUSDT" },
  { name: "Compound", symbol: "COMP", tradingViewSymbol: "BINANCE:COMPUSDT" },
  { name: "Synthetix", symbol: "SNX", tradingViewSymbol: "BINANCE:SNXUSDT" },
  { name: "dYdX", symbol: "DYDX", tradingViewSymbol: "BINANCE:DYDXUSDT" },
  { name: "Mina", symbol: "MINA", tradingViewSymbol: "BINANCE:MINAUSDT" },
  { name: "Chiliz", symbol: "CHZ", tradingViewSymbol: "BINANCE:CHZUSDT" },
  { name: "Zilliqa", symbol: "ZIL", tradingViewSymbol: "BINANCE:ZILUSDT" },
  { name: "Oasis Network", symbol: "ROSE", tradingViewSymbol: "BINANCE:ROSEUSDT" },
  { name: "Kava", symbol: "KAVA", tradingViewSymbol: "BINANCE:KAVAUSDT" },
  { name: "Celo", symbol: "CELO", tradingViewSymbol: "BINANCE:CELOUSDT" },
  { name: "Dash", symbol: "DASH", tradingViewSymbol: "BINANCE:DASHUSDT" },
  { name: "Zcash", symbol: "ZEC", tradingViewSymbol: "BINANCE:ZECUSDT" },
  { name: "Tezos", symbol: "XTZ", tradingViewSymbol: "BINANCE:XTZUSDT" },
  { name: "MultiversX", symbol: "EGLD", tradingViewSymbol: "BINANCE:EGLDUSDT" },
  { name: "NEO", symbol: "NEO", tradingViewSymbol: "BINANCE:NEOUSDT" },
  { name: "IOTA", symbol: "IOTA", tradingViewSymbol: "BINANCE:IOTAUSDT" },
  { name: "Kusama", symbol: "KSM", tradingViewSymbol: "BINANCE:KSMUSDT" },
  { name: "1inch", symbol: "1INCH", tradingViewSymbol: "BINANCE:1INCHUSDT" },
  { name: "PancakeSwap", symbol: "CAKE", tradingViewSymbol: "BINANCE:CAKEUSDT" },
  { name: "Raydium", symbol: "RAY", tradingViewSymbol: "BINANCE:RAYUSDT" },
  { name: "Terra Classic", symbol: "LUNC", tradingViewSymbol: "BINANCE:LUNCUSDT" },
  { name: "Axie Infinity", symbol: "AXS", tradingViewSymbol: "BINANCE:AXSUSDT" },
  { name: "STEPN", symbol: "GMT", tradingViewSymbol: "BINANCE:GMTUSDT" },
  { name: "Ethena", symbol: "ENA", tradingViewSymbol: "BINANCE:ENAUSDT" },
  { name: "ORDI", symbol: "ORDI", tradingViewSymbol: "BINANCE:ORDIUSDT" },
  { name: "SATS", symbol: "SATS", tradingViewSymbol: "BINANCE:1000SATSUSDT" },
  { name: "Blur", symbol: "BLUR", tradingViewSymbol: "BINANCE:BLURUSDT" },
  { name: "Mask Network", symbol: "MASK", tradingViewSymbol: "BINANCE:MASKUSDT" },
  { name: "SKALE", symbol: "SKL", tradingViewSymbol: "BINANCE:SKLUSDT" },
  { name: "Holo", symbol: "HOT", tradingViewSymbol: "BINANCE:HOTUSDT" },
  { name: "Qtum", symbol: "QTUM", tradingViewSymbol: "BINANCE:QTUMUSDT" },
  { name: "Basic Attention Token", symbol: "BAT", tradingViewSymbol: "BINANCE:BATUSDT" },
  { name: "Ravencoin", symbol: "RVN", tradingViewSymbol: "BINANCE:RVNUSDT" },
  { name: "Ankr", symbol: "ANKR", tradingViewSymbol: "BINANCE:ANKRUSDT" },
  { name: "ConstitutionDAO", symbol: "PEOPLE", tradingViewSymbol: "BINANCE:PEOPLEUSDT" },
  { name: "Memecoin", symbol: "MEME", tradingViewSymbol: "BINANCE:MEMEUSDT" },
  { name: "Notcoin", symbol: "NOT", tradingViewSymbol: "BINANCE:NOTUSDT" }
];
