import type { PromptTemplates } from "./types.js";

export const defaultPromptTemplates: PromptTemplates = {
  keywords: [
    "Bạn là chuyên gia nghiên cứu từ khóa cho hệ thống tạo bài viết.",
    "",
    "Nhiệm vụ:",
    "Phân tích danh sách từ khóa thu thập được (kèm volume), sau đó chọn lọc ra 8 từ khóa tốt nhất để viết bài (1 chính, 7 phụ).",
    "",
    "Đầu vào:",
    "- Từ khóa gốc: {{keyword}}",
    "- Ngôn ngữ bài viết: {{language}}",
    "- Dữ liệu từ khóa: \n{{semrush_data}}",
    "",
    "Yêu cầu đầu ra:",
    "1. CHỈ ĐƯỢC CHỌN đúng 8 từ khóa CÓ SẴN trong 'Dữ liệu từ khóa'. GIỮ NGUYÊN VĂN 100%, tuyệt đối không tự chế ra từ mới hay sửa đổi từ khóa.",
    "2. Mỗi từ khóa phải có: keyword, intent, cluster.",
    "3. Ưu tiên từ khóa có volume cao và có thể phát triển thành bài viết độc lập.",
    "4. Tránh các từ khóa quá rộng hoặc trùng nghĩa.",
    "",
    "OUTPUT CONTRACT:",
    "- Trả về đúng 1 JSON object.",
    "- Từ khóa (keyword) PHẢI copy y hệt từ 'Dữ liệu từ khóa'.",
    "- Không markdown, không text giải thích, không comment, không trailing comma.",
    "- intent chỉ được là: informational, commercial, comparison, transactional.",
    '- cluster là nhãn ngắn gọn dạng string, ví dụ: "cơ bản", "so sánh", "công cụ".',
    "",
    "JSON SHAPE:",
    '{',
    '  "keywordIdeas": [',
    '    {',
    '      "keyword": "string",',
    '      "intent": "informational",',
    '      "cluster": "string"',
    '    }',
    '  ]',
    '}'
  ].join("\n"),
  brief: [
    "Bạn là biên tập viên lập định hướng bài cho bài viết SEO.",
    "",
    "Nhiệm vụ:",
    "Phân tích nội dung của Top 10 bài viết đối thủ đang xếp hạng cao để tìm ra phương án triển khai. Định hướng cần kế thừa điểm mạnh của đối thủ và đề xuất góc tiếp cận (angle) tốt hơn, khác biệt hơn.",
    "",
    "Đầu vào:",
    "- Từ khóa chính: {{primary_keyword}}",
    "- Từ khóa phụ: {{secondary_keywords}}",
    "- Ngôn ngữ bài viết: {{language}}",
    "- Dữ liệu Top 10 đối thủ: \n{{competitor_data}}",
    "",
    "Yêu cầu đầu ra:",
    "1. Xác định search intent chính.",
    "2. Đề xuất góc tiếp cận phù hợp.",
    "3. Liệt kê semantic topics cần phủ.",
    "4. Gợi ý các câu hỏi FAQ quan trọng.",
    "5. Rút ra competitorInsights cho từng bài trong Top 10 của từ khóa chính. Mỗi insight phải chỉ ra cách bài đối thủ triển khai SEO, điểm mạnh, khoảng trống và điều nên kế thừa/cải thiện.",
    "",
    "OUTPUT CONTRACT:",
    "- Trả về đúng 1 JSON object.",
    "- searchIntent và angle là string ngắn, rõ, dùng được ngay.",
    "- semanticTopics là mảng string.",
    "- candidateFaqs là mảng string dạng câu hỏi.",
    "- competitorInsights là mảng object, tối đa 10 item, xếp theo rank SERP.",
    "- Không markdown, không text ngoài JSON, không comment.",
    "",
    "JSON SHAPE:",
    '{',
    '  "brief": {',
    '    "searchIntent": "string",',
    '    "angle": "string",',
    '    "semanticTopics": ["string"],',
    '    "candidateFaqs": ["string"],',
    '    "competitorInsights": [',
    '      {',
    '        "rank": 1,',
    '        "keyword": "string",',
    '        "url": "string",',
    '        "title": "string",',
    '        "contentSummary": "string",',
    '        "seoIntent": "string",',
    '        "outlinePattern": "string",',
    '        "strengths": ["string"],',
    '        "gaps": ["string"],',
    '        "recommendedTakeaway": "string"',
    '      }',
    '    ]',
    '  }',
    '}'
  ].join("\n"),
  outline: [
    "Bạn là người lập dàn ý cho bài viết chuẩn SEO.",
    "",
    "Nhiệm vụ:",
    "Gộp các phân tích từ Định hướng bài (Brief) và Dữ liệu Top 10 đối thủ để lập dàn ý rõ ràng, đủ ngắn để editor kiểm nhanh nhưng đủ ý để writer viết bài.",
    "",
    "Đầu vào:",
    "- Từ khóa chính: {{primary_keyword}}",
    "- Từ khóa phụ: {{secondary_keywords}}",
    "- Ngôn ngữ bài viết: {{language}}",
    "- Dữ liệu Top 10 đối thủ: \n{{competitor_data}}",
    "- Keyword plan có volume: \n{{keyword_plan}}",
    "- 10 insight đối thủ: \n{{competitor_insights}}",
    "- Search intent: {{search_intent}}",
    "- Góc bài: {{angle}}",
    "- Semantic topics: {{semantic_topics}}",
    "- FAQ: {{candidate_faqs}}",
    "- Brief JSON: {{brief_json}}",
    "",
    "Yêu cầu đầu ra:",
    "1. Đưa ra title bài viết.",
    "2. Đưa ra hướng mở bài.",
    "3. Chia bài thành các phần hợp lý. BẮT BUỘC kết hợp cách trình bày hay nhất từ 10 insight đối thủ, phủ đủ nội dung đối thủ có, và bổ sung ít nhất 1-2 H2 mới lạ mà đối thủ chưa đề cập.",
    "4. BẮT BUỘC phủ toàn bộ từ khóa trong Keyword plan. Từ khóa volume cao nên nằm trong title, introDirection, heading hoặc bullet quan trọng.",
    "5. Mỗi phần có bullet ý chính cần viết.",
    "6. Trả thêm keywordCoverage để chỉ rõ từng keyword được xử lý ở đâu trong outline.",
    "",
    "OUTPUT CONTRACT:",
    "- Trả về đúng 1 JSON object.",
    "- title và introDirection là string.",
    "- sections là mảng object, mỗi object có heading và bullets.",
    "- keywordCoverage là mảng object chứa keyword, monthlyVolume, intent, placement.",
    "- bullets là mảng string ngắn, đi thẳng ý.",
    "- Tuyệt đối không viết self-correction, nhận xét về schema, hoặc lời giải thích quá trình suy nghĩ vào bất kỳ field nào.",
    "- Không markdown, không text ngoài JSON, không comment.",
    "",
    "JSON SHAPE:",
    '{',
    '  "outline": {',
    '    "title": "string",',
    '    "introDirection": "string",',
    '    "sections": [',
    '      {',
    '        "heading": "string",',
    '        "bullets": ["string"]',
    '      }',
    '    ],',
    '    "keywordCoverage": [',
    '      {',
    '        "keyword": "string",',
    '        "monthlyVolume": 100,',
    '        "intent": "informational",',
    '        "placement": "string"',
    '      }',
    '    ]',
    '  }',
    '}'
  ].join("\n"),
  draft: [
    "Bạn là người viết bản nháp đầu tiên cho bài viết.",
    "",
    "Nhiệm vụ:",
    "Viết bản nháp hoàn chỉnh, dễ đọc và sẵn cho biên tập chỉnh sửa.",
    "",
    "Đầu vào:",
    "- Từ khóa chính: {{primary_keyword}}",
    "- Từ khóa phụ: {{secondary_keywords}}",
    "- Ngôn ngữ bài viết: {{language}}",
    "- Tiêu đề dàn ý: {{outline_title}}",
    "- Hướng mở bài: {{outline_intro_direction}}",
    "- Các section: {{outline_sections}}",
    "- Outline JSON: {{outline_json}}",
    "",
    "Yêu cầu đầu ra:",
    "1. Viết theo đúng dàn ý đã có.",
    "2. Giữ văn phong rõ ràng, tự nhiên.",
    "3. Không nhồi từ khóa.",
    "4. Sinh luôn title, slug, meta title và meta description.",
    "",
    "OUTPUT CONTRACT:",
    "- Trả về đúng 1 JSON object.",
    "- Mọi field đều là string.",
    "- slug chỉ dùng lowercase và dấu gạch nối.",
    "- markdown phải là 1 string JSON hợp lệ duy nhất, xuống dòng bằng \\n.",
    "- Không bọc markdown code fence.",
    "- Không text ngoài JSON, không comment, không trailing comma.",
    "",
    "JSON SHAPE:",
    '{',
    '  "draft": {',
    '    "title": "string",',
    '    "slug": "string",',
    '    "excerpt": "string",',
    '    "metaTitle": "string",',
    '    "metaDescription": "string",',
    '    "markdown": "string"',
    '  }',
    '}'
  ].join("\n"),
  links: [
    "Bạn là người review internal link cho bài viết.",
    "",
    "Nhiệm vụ:",
    "Đọc bản nháp và trích xuất danh sách từ khóa hoặc cụm từ trong bài đang là điểm gắn internal link hợp lý nhất.",
    "",
    "Đầu vào:",
    "- Từ khóa chính: {{primary_keyword}}",
    "- Từ khóa phụ: {{secondary_keywords}}",
    "- Ngôn ngữ bài viết: {{language}}",
    "- Tiêu đề bản nháp: {{draft_title}}",
    "- Toàn bộ bản nháp: {{draft_markdown}}",
    "",
    "Yêu cầu đầu ra:",
    "1. Chỉ đề xuất các anchor thực sự đã xuất hiện trong bản nháp.",
    "2. Mỗi anchor cần có sourceContext, reason và confidence.",
    "3. Không cần quyết định URL đích trong prompt này.",
    "4. Ưu tiên cụm từ có thể điều hướng sang bài chuyên sâu liên quan.",
    "",
    "OUTPUT CONTRACT:",
    "- Trả về đúng 1 JSON object.",
    "- anchorSuggestions là mảng object.",
    "- Mỗi object có: anchor, sourceContext, reason, confidence.",
    "- confidence là số nguyên từ 0 đến 100.",
    "- Không markdown, không text ngoài JSON, không comment.",
    "",
    "JSON SHAPE:",
    '{',
    '  "anchorSuggestions": [',
    '    {',
    '      "anchor": "string",',
    '      "sourceContext": "string",',
    '      "reason": "string",',
    '      "confidence": 85',
    '    }',
    '  ]',
    '}'
  ].join("\n")
};
