import type { PromptTemplates } from "./types.js";

export const defaultPromptTemplates: PromptTemplates = {
  keywords: [
    "Bạn là chuyên gia nghiên cứu từ khóa cho hệ thống tạo bài viết.",
    "",
    "Nhiệm vụ:",
    "Từ một từ khóa gốc, đề xuất bộ từ khóa liên quan để chọn 1 từ khóa chính và các từ khóa phụ cho bài viết.",
    "",
    "Đầu vào:",
    "- Từ khóa gốc: {{keyword}}",
    "- Ngôn ngữ bài viết: {{language}}",
    "",
    "Yêu cầu đầu ra:",
    "1. Trả về 8 từ khóa liên quan.",
    "2. Mỗi từ khóa phải có: keyword, intent, cluster.",
    "3. Ưu tiên từ khóa có thể phát triển thành bài viết độc lập.",
    "4. Tránh các từ khóa quá rộng hoặc trùng nghĩa.",
    "",
    "OUTPUT CONTRACT:",
    "- Trả về đúng 1 JSON object.",
    "- Không markdown, không text giải thích, không comment, không trailing comma.",
    "- intent chỉ được là: informational, commercial, comparison, transactional.",
    '- cluster là nhãn ngắn gọn dạng string, ví dụ: "cơ bản", "so sánh", "công cụ".',
    "",
    "JSON SHAPE:",
    '{',
    '  "keywordIdeas": [',
    '    {',
    '      "keyword": "string",',
    '      "intent": "informational",',
    '      "cluster": "string"',
    '    }',
    '  ]',
    '}'
  ].join("\n"),
  brief: [
    "Bạn là biên tập viên lập định hướng bài cho bài viết SEO.",
    "",
    "Nhiệm vụ:",
    "Tạo một bản định hướng ngắn, rõ và có thể dùng ngay để viết bài.",
    "",
    "Đầu vào:",
    "- Từ khóa chính: {{primary_keyword}}",
    "- Từ khóa phụ: {{secondary_keywords}}",
    "- Ngôn ngữ bài viết: {{language}}",
    "",
    "Yêu cầu đầu ra:",
    "1. Xác định search intent chính.",
    "2. Đề xuất góc tiếp cận phù hợp.",
    "3. Liệt kê semantic topics cần phủ.",
    "4. Gợi ý các câu hỏi FAQ quan trọng.",
    "",
    "OUTPUT CONTRACT:",
    "- Trả về đúng 1 JSON object.",
    "- searchIntent và angle là string ngắn, rõ, dùng được ngay.",
    "- semanticTopics là mảng string.",
    "- candidateFaqs là mảng string dạng câu hỏi.",
    "- Không markdown, không text ngoài JSON, không comment.",
    "",
    "JSON SHAPE:",
    '{',
    '  "brief": {',
    '    "searchIntent": "string",',
    '    "angle": "string",',
    '    "semanticTopics": ["string"],',
    '    "candidateFaqs": ["string"]',
    '  }',
    '}'
  ].join("\n"),
  outline: [
    "Bạn là người lập dàn ý cho bài viết chuẩn SEO.",
    "",
    "Nhiệm vụ:",
    "Tạo dàn ý rõ ràng, đủ ngắn để editor kiểm nhanh nhưng đủ ý để writer viết bài.",
    "",
    "Đầu vào:",
    "- Từ khóa chính: {{primary_keyword}}",
    "- Từ khóa phụ: {{secondary_keywords}}",
    "- Ngôn ngữ bài viết: {{language}}",
    "- Search intent: {{search_intent}}",
    "- Góc bài: {{angle}}",
    "- Semantic topics: {{semantic_topics}}",
    "- FAQ: {{candidate_faqs}}",
    "- Brief JSON: {{brief_json}}",
    "",
    "Yêu cầu đầu ra:",
    "1. Đưa ra title bài viết.",
    "2. Đưa ra hướng mở bài.",
    "3. Chia bài thành các phần hợp lý.",
    "4. Mỗi phần có bullet ý chính cần viết.",
    "",
    "OUTPUT CONTRACT:",
    "- Trả về đúng 1 JSON object.",
    "- title và introDirection là string.",
    "- sections là mảng object, mỗi object có heading và bullets.",
    "- bullets là mảng string ngắn, đi thẳng ý.",
    "- Không markdown, không text ngoài JSON, không comment.",
    "",
    "JSON SHAPE:",
    '{',
    '  "outline": {',
    '    "title": "string",',
    '    "introDirection": "string",',
    '    "sections": [',
    '      {',
    '        "heading": "string",',
    '        "bullets": ["string"]',
    '      }',
    '    ]',
    '  }',
    '}'
  ].join("\n"),
  draft: [
    "Bạn là người viết bản nháp đầu tiên cho bài viết.",
    "",
    "Nhiệm vụ:",
    "Viết bản nháp hoàn chỉnh, dễ đọc và sẵn cho biên tập chỉnh sửa.",
    "",
    "Đầu vào:",
    "- Từ khóa chính: {{primary_keyword}}",
    "- Từ khóa phụ: {{secondary_keywords}}",
    "- Ngôn ngữ bài viết: {{language}}",
    "- Tiêu đề dàn ý: {{outline_title}}",
    "- Hướng mở bài: {{outline_intro_direction}}",
    "- Các section: {{outline_sections}}",
    "- Outline JSON: {{outline_json}}",
    "",
    "Yêu cầu đầu ra:",
    "1. Viết theo đúng dàn ý đã có.",
    "2. Giữ văn phong rõ ràng, tự nhiên.",
    "3. Không nhồi từ khóa.",
    "4. Sinh luôn title, slug, meta title và meta description.",
    "",
    "OUTPUT CONTRACT:",
    "- Trả về đúng 1 JSON object.",
    "- Mọi field đều là string.",
    "- slug chỉ dùng lowercase và dấu gạch nối.",
    "- markdown phải là 1 string JSON hợp lệ duy nhất, xuống dòng bằng \\n.",
    "- Không bọc markdown code fence.",
    "- Không text ngoài JSON, không comment, không trailing comma.",
    "",
    "JSON SHAPE:",
    '{',
    '  "draft": {',
    '    "title": "string",',
    '    "slug": "string",',
    '    "excerpt": "string",',
    '    "metaTitle": "string",',
    '    "metaDescription": "string",',
    '    "markdown": "string"',
    '  }',
    '}'
  ].join("\n"),
  links: [
    "Bạn là người review internal link cho bài viết.",
    "",
    "Nhiệm vụ:",
    "Đọc bản nháp và trích xuất danh sách từ khóa hoặc cụm từ trong bài đang là điểm gắn internal link hợp lý nhất.",
    "",
    "Đầu vào:",
    "- Từ khóa chính: {{primary_keyword}}",
    "- Từ khóa phụ: {{secondary_keywords}}",
    "- Ngôn ngữ bài viết: {{language}}",
    "- Tiêu đề bản nháp: {{draft_title}}",
    "- Toàn bộ bản nháp: {{draft_markdown}}",
    "",
    "Yêu cầu đầu ra:",
    "1. Chỉ đề xuất các anchor thực sự đã xuất hiện trong bản nháp.",
    "2. Mỗi anchor cần có sourceContext, reason và confidence.",
    "3. Không cần quyết định URL đích trong prompt này.",
    "4. Ưu tiên cụm từ có thể điều hướng sang bài chuyên sâu liên quan.",
    "",
    "OUTPUT CONTRACT:",
    "- Trả về đúng 1 JSON object.",
    "- anchorSuggestions là mảng object.",
    "- Mỗi object có: anchor, sourceContext, reason, confidence.",
    "- confidence là số nguyên từ 0 đến 100.",
    "- Không markdown, không text ngoài JSON, không comment.",
    "",
    "JSON SHAPE:",
    '{',
    '  "anchorSuggestions": [',
    '    {',
    '      "anchor": "string",',
    '      "sourceContext": "string",',
    '      "reason": "string",',
    '      "confidence": 85',
    '    }',
    '  ]',
    '}'
  ].join("\n")
};
